#!/usr/bin/env bash
#Bash script that displays a message when it is terminated
trap 'echo "I am invincible!!!"' SIGTERM
counter=2
while [ $counter -gt 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
