#!/usr/bin/env bash
#Creating a script that uses if, else if and else statements
counter=1
while [ $counter -lt 11 ]; do
    if [ $counter -eq 4 ]
    then
	echo "bad luck"
    elif [ $counter -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    let counter=counter+1
done
