#!/usr/bin/env bash
#Creating a script that uses a nested loop
minutes=1
hours=0
while [ $hours -lt 13 ]; do
    echo Hour: $hours
    while [ $minutes -lt 60 ]; do
	echo $minutes
	let minutes+=1
    done
    let minutes=1
    let hours+=1
done
